### ISSUE TITLE
Fix for OSX

### ISSUE THREAD

**Issue by axyr** [brandonjjon/tp-importer#3]
If you run this on osx you will get this message:..

```env: node\r: No such file or directory```

A solution can be found here:

https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

**Comment by brandonjjon** [comment]
@axyr This was developed and tested on osx, were you still having this issue?

**Comment by axyr** [comment]
it's now working, but if i remember will, I had to use that fix..
but it's been a while :)

**Comment by brandonjjon** [comment]
Glad you got it working :slightly_smiling_face:
